@startuml
'default
top to bottom direction
user1 --> (Usecase 1)
user2 --> (Usecase 2)
@enduml

@startuml
' 你可以用 left to right direction 命令改变图示方向
left to right direction
user1 --> (Usecase 1)
user2 --> (Usecase 2)
@enduml